# inventories/prod/group_vars/all/services.yml
---
# Global lookup table for service definitions.

services:
  proxmox:
    hostname: "gamecube"
    domain: "gamecube.raskal.io"
    ip: "192.168.0.20"
    port: 8006

  adguard:
    hostname: "link-cable"
    domain: "link-cable.raskal.io"
    ip: "192.168.0.30"
    port: 3000
    vmid: 105

# Global variables
root_domain: "raskal.io"
acme_email: "labs@raskal.io"
