$ANSIBLE_VAULT;1.1;AES256
61336132326262373839316435616638613531383566666133336132653664613335633232396233
3162363834373730386530613834326165613531646163640a313566343633346431363433326432
64613135626436323763356333343939616464396132656438373963383066663436313363666436
3964346236313732660a646131336263393462653633376461646663316432336264386532643366
36353639316461333238306233333132343662393431363833353133393936393035646632346461
31336161336264643236656664373037666438666332346438366631643361313130356433343735
63336134643462613631356537663265666461396333316366626261616633343464663338343234
66356138353331353837346461643963333135356364386636343764323465316138626638333661
37613830316564646332343133616433626662323765646364383838336331646235613030643361
30656463343737336432623837346466356364653832356433393765333066653161366334656563
36613935303265386437366433333965663763316233633233343632333436663732323032303036
39386333303835626438303633303237303264366562303964646161643834663838613766356262
38613030316138636133336163626165616231653965373334623538633664363337336231643936
64653165306663306638336138383032303462346165643933333836313732333431616539323763
393534616366623336303566363337346138
