$ANSIBLE_VAULT;1.1;AES256
66623731613339323161336364343162663432323333643636613839333165613439333032613831
3136653933343563326365376262663330626461336633330a346132653539393331303934313533
62366131636565666562306366613630626436666365306237376335313130666537633531663838
3138383034393039330a376438336138373334346633333232383132633334316435656633376663
63356231633732633431626630316561383064633665386366383935656434326438326631323362
62663235626533343237353235623131393031313864333963346435323832326365383133663263
61326563313265636136323265333639313563323863353866633861643266616134623661366332
65373362383463386534356163336663336138306461666265326663346336623538623534386333
3166
