---
netbird_domain: "randnet.raskal.io"
netbird_mgmt_port: 33073
netbird_signal_port: 33080
netbird_pre_shared_key: "randnet"

netbird_version: "0.60.2"
netbird_os: "linux"
netbird_arch: "amd64"

netbird_mgmt_bin_path: /usr/local/bin/netbird-mgmt
