---
# Email used for ACME/Letâ€™s Encrypt
caddy_email: "labs@raskal.io"

# Root landing page domain (optional)
caddy_root_domain: "raskal.io"

# =========================
# NetBird LXC (randnet)
# =========================
caddy_netbird_upstream: "192.168.0.32"

# NetBird dashboard UI
caddy_netbird_dashboard_port: 80

# NetBird API service
caddy_netbird_api_port: 33073

# NetBird Signal (HTTP fallback + gRPC)
caddy_netbird_signal_http_port: 80
caddy_netbird_signal_grpc_port: 33080

# NetBird Relay
caddy_netbird_relay_port: 61820

# =========================
# Keycloak LXC (file-select)
# =========================
caddy_keycloak_upstream: "192.168.0.36"

# =========================
# AdGuard LXC (link-cable)
# =========================
caddy_adguard_upstream: "192.168.0.30"
caddy_adguard_port: 3000

# =========================
# Proxmox (gamecube)
# =========================
caddy_proxmox_upstream: "192.168.0.20"
caddy_proxmox_port: 8006

# =========================
# Domains
# =========================
caddy_netbird_domain: "randnet.raskal.io"
caddy_keycloak_domain: "file-select.raskal.io"
caddy_adguard_domain: "link-cable.raskal.io"
caddy_proxmox_domain: "gamecube.raskal.io"
