1# roles/lxc-adguard/defaults/main.yml
---
# --- Application Pathing ---
adguard_download_url: "https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz"

# --- AdGuard Config Defaults (Used in AdGuardHome.yml.j2) ---
adguard_bind_hosts:
  - "{{ services['adguard'].ip }}" # Bind to its own IP
  
adguard_upstream_dns:
  - https://dns10.quad9.net/dns-query
  - https://dns11.quad9.net/dns-query

adguard_bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10

adguard_web_port: "{{ services['adguard'].port }}"
adguard_dns_port: 53
adguard_api_user: "raskal" # Hash must be in Vault
