---
pve_lxc_containers:
  - vmid: 105
    hostname: "link-cable"
    ip: "192.168.0.30/24"
    gateway: "192.168.0.1"
    memory: 1024
    cores: 2
    rootfs_size: "8"
    state: "started"
    mounts:
      - id: 0
        source: "/box1/apps/link-cable"
        target: "/var/lib/adguardhome"
        backup: 0

  - vmid: 104
    hostname: "warp-zone"
    ip: "192.168.0.34/24"
    gateway: "192.168.0.1"
    memory: 1024
    cores: 2
    rootfs_size: "8"
    state: "started"
    mounts:
      - id: 0
        source: "/box1/apps/warp-zone"
        target: "/etc/caddy"
        backup: 0

  - vmid: 106
    hostname: "file-select"
    ip: "192.168.0.36/24"
    gateway: "192.168.0.1"
    memory: 4096
    cores: 2
    rootfs_size: "16"
    state: "started"
    mounts:
      - id: 0
        source: "/box1/apps/file-select"
        target: "/opt/keycloak"
        backup: 0

pve_vms:
  - vmid: 102
    name: "randnet"
    description: "NetBird VM"
    memory: 2048
    cores: 2
    ip: "192.168.0.32/24"
    gateway: "192.168.0.1"
    storage: "disc"
    disk: "16G"
    net_bridge: "vmbr0"
