---
dolphin_api_group: "labs"
dolphin_api_user: "labs@pve"

dolphin_datacenter_cfg:
  keyboard: "en-us"
  console: "shell"

dolphin_storages:
  - id: "local-zfs"
    type: "zfspool"
    pool: "rpool/data"
    content: "images,rootdir"
