---
- name: Check that Proxmox is installed
  command: pveversion
  register: dolphin_pveversion
  changed_when: false
  failed_when: dolphin_pveversion.rc != 0

- name: Run dolphin configuration tasks
  include_tasks: configure.yml
