# inventories/prod/host_vars/randnet.yml

ansible_host: 192.168.0.32
ansible_user: root
ansible_ssh_private_key_file: /root/.ssh/id_ed25519_ansible

# Optional, only used if base-debian manages CT networking:
base_debian_network_address: "192.168.0.32/24"
