# inventories/prod/host_vars/warp-zone.yml

ansible_host: 192.168.0.34
ansible_user: root
ansible_ssh_private_key_file: /root/.ssh/id_ed25519_ansible

# Optional, only used if base-debian manages CT networking:
base_debian_network_address: "192.168.0.34/24"

# Caddy / ACME email (used in Caddyfile.j2)
caddy_email: "labs@raskal.io"

