---
# Extra packages to ensure on every Debian host/container.
# Override in host_vars or group_vars if you want a different set.
base_debian_packages:
  - ca-certificates
  - curl
  - vim-tiny
  - htop
  - sudo

# Whether to perform a full dist upgrade.
base_debian_do_dist_upgrade: true
