# netbird_stack.yml
base_debian_dns_servers:
  - "192.168.0.30"  # AdGuard
  - "1.1.1.1"       # Fallback

base_debian_dns_search_domains:
  - "lan"

base_debian_network_gateway: "192.168.0.1"
base_debian_network_interface: "eth0"

pve_lxc_ssh_bootstrap_pubkey_path: /root/.ssh/id_ed25519_ansible.pub
