---
# Physical uplink NIC on gamecube
olimar_uplink_iface: eno1

# Bridge definitions managed by Olimar
olimar_bridges:
  # Primary management / LAN bridge
  - name: vmbr0
    method: static
    address: 192.168.0.20
    netmask: 255.255.255.0
    gateway: 192.168.0.1
    bridge_ports: "{{ olimar_uplink_iface }}"
    bridge_stp: "off"
    bridge_fd: "0"
    autostart: true

  # Example internal bridge (no IP yet)
  - name: vmbr1
    method: manual
    bridge_ports: "none"
    bridge_stp: "off"
    bridge_fd: "0"
    autostart: true
