---
- name: Provision NetBird VM
  hosts: gamecube
  gather_facts: false
  roles:
    - pve-vm

- name: Bootstrap Debian inside NetBird VM
  hosts: randnet
  gather_facts: false

  pre_tasks:
    - wait_for_connection:
        timeout: 70

  roles:
    - base-debian
    - ssh-base
    - netbird-server
