---
pve_vm_defaults:
  memory: 2048
  cores: 2
  storage: "disc"
  disk: "16G"
  net_bridge: "vmbr0"

  # Cloud-init disk target (must support "images")
  cloudinit_storage: "disc"

  # Path to the base Debian cloud image
  iso_path: "/root/isos/debian-12-generic-amd64.qcow2"
