---
- name: Install coturn package
  ansible.builtin.apt:
    name: coturn
    state: present
    update_cache: yes

- name: Deploy coturn config
  ansible.builtin.template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
    mode: "0644"

- name: Enable coturn service
  ansible.builtin.systemd:
    name: coturn
    enabled: yes
    state: restarted
